### ISSUE TITLE
Programming with C/C++

### ISSUE THREAD

**Issue by carlosperate** [andrew-t/microbit#1]
Hi,

Just found this repository from a github search. Apologies to open an issue for just a suggestion, but I guess this is the quickest way to share some info.

I noticed you mentioned in your readme:

> Personally, I would like a closer-to-the-metal language than the Javascript-like one that I can compile offline, but the current setup is pretty impressive.

Have you had a chance to look at the mbed DAL for easy programming n C/C++? http://lancaster-university.github.io/microbit-docs

**Comment by andrew-t** [comment]
I have not. Last time I checked, some vital component or other hadn't been made public. Has that changed or is this a separate thing I hadn't found?

**Comment by carlosperate** [comment]
This is the Lancaster DAL becoming public yes, so you can use offline yotta with the DAL for easy development using C/C++.

**Comment by andrew-t** [comment]
That's good news. I was worried that wouldn't come out for ages.

I probably haven't time to look at it properly for a good while, but I
definitely will eventually.
